### ISSUE TITLE
Whis is the version of pycolmap?

### ISSUE THREAD

**Issue by star-LTH** [Kunhao-Liu/ViewExtrapolator#2]
Hi,there!
When I ran the code, I met the mistake:
cannot import name 'SceneManager' from 'pycolmap'
I think it comes from the version of pycolmap. But in the requirement.txt I do not find it. So would you mind tell me the version of pycolmap you use? thank you!

**Comment by Kunhao-Liu** [comment]
Hi, we use pycolmap v0.0.1.
